sudo: required
services:
- docker
env:
  global:
  - DOCKER_USERNAME=bodsch
  - BUILD_DATE=$(date +"%Y-%m-%d")
  - BUILD_VERSION=$(date +"%y%m")
  - secure: Y6VuqPJjl+e10SSVj0QWOEhihaMmIDeizJfxT79ly9WGd83OwRIBarrWpfzBnwjsqKGyHroWQtGSdxppqY8uGn182QTKDm1CyxJ1a9w3CW4gf6fOTMv0jjiGPkQPeEogDnThkM8RD2DUeuNoTxLB/CRayaUBRR7fduV8c1qdfJO5Zxh77i2GyM0e1C2ck+34JwNoxto/ggR7FPa6JI3vDyKgNygCXdjge60TEYG03upTHuc06TJRe2GK0nEIzVsaqDshUo0oo3ls0kDxcDrMrT+QenJ3pUz6sttJBhYimDBBjHc/NRqwe2ccjERcEtS7vUJUL5OCyCAsnjJikN8tDl6kl2Hv9CfjjSI8sLS9nrmXn8ZOAKDnOfV3nkI4knSTT+GG+KiOq04lgsi5uAvBIVBlZFKmKuUvtLsvnsFBlIjvRG69iPs34EzajEdXj028xKqhPKCRaLuik2Ws1FnnVbh94zQ7UUJQXKHsbcYo5ffFTkLkEMx9DRLe1NdtxxJj8kJ6kwMi9W9WMkvMxWugxd4ya/HTISY+VER8VkqMQVTENKSpPCOjpPU/8Wx37cFELWv2Zfyey/IEdZauZLcNvdKew9MHqsqUCK2u0FCEkwwP55H8Hp97NN/fqh2zL5f5g052uOEZi+TaNCjPcp3qLz/SSc59KbOQWSdENCyx8wA=
  matrix:
  - NGINX_VERSION=${NGINX_VERSION:-1.12.2}
  - NGINX_VERSION=latest
jobs:
  include:
  - stage: build
    script:
    - make build
  - stage: run
    script:
    - make build
    - make start
    - docker ps | grep -q nginx
  - stage: publish
    script:
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - make publish
    - docker logout
