sudo: required

services:
  - docker

install:
  - docker build --tag bodsch/docker-nginx .
  - docker run --detach --name nginx bodsch/docker-nginx

script:
  - docker ps | grep -q nginx


after_success:
  - |
    if ( [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ ! -z ${DOCKER_HUB_TOKEN} ]] ) ; then \
      curl \
        --request POST \
        --header "Content-Type: application/json"  \
        --data '{"source_type":"Branch","source_name":"master"}' \
        https://registry.hub.docker.com/u/bodsch/docker-icinga2/trigger/${DOCKER_HUB_TOKEN}/ ; \
    fi
