---
version: '3.3'

services:

  nginx:
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - BUILD_DATE
        - BUILD_VERSION
        - BUILD_TYPE
        - NGINX_VERSION
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    hostname: nginx
